**************************** LABEL THE VARS ***********************************
lab var dlrdeposits "Real deposit growth"
lab var dlrdeposits_hhs_w "Real HH deposit growth"
lab var election "$\text{Election}_{it}$"
lab var inflation_cpi_lag "$\text{Inflation CPI}_{it-1}$"
lab var lrgdppc_usd_lag "$\log(\text{Real GDP per capita}_{it-1})$"
lab var dlrgdp_lcu_lag "$\text{Real GDP growth}_{it-1}$"
lab var unempl_ilo_lag "$\text{Unemployment}_{it-1}$"
lab var capitaltoassets_lag "$\text{Capital ratio}_{it-1}$"
lab var depositstogdp_lag "$\text{Deposits to GDP}_{it-1}$"
lab var liqratio_lag "$\text{Liquidity ratio}_{it-1}$"
lab var hf_prights_lag "$\text{Property rights}_{it-1}$"
lab var ti_cpi_lag "$\text{Corruption perception}_{it-1}$"
lab var h_polcon3 "$\text{Checks \& balances}_{it}$"
lab var lowpolcon "$\text{Weak C\&B}_{it}$"
lab var clelec "$\text{Close election}_{it}$"
lab var sureelec "$\text{Certain election}_{it}$"
lab var depinsurance_lag "$\text{Deposit insurance}_{it-1}$"
lab var execrlc1 "$\text{Incumbent's affiliation}_{it}$"
lab var intercb1 "$\text{Election}_{it}$ $\times$ $\text{Weak C\&B}_{it}$"
lab var interdi "$\text{Election}_{it}$ $\times$ $\text{Deposit insurance}_{it-1}$"
lab var intercent "$\text{Election}_{it}$ $\times$ $\text{Center}_{it}$"
lab var interleft "$\text{Election}_{it}$ $\times$ $\text{Left}_{it}$"
lab var platform1 "$\text{Right}_{it}$"
lab var platform2 "$\text{Center}_{it}$"
lab var platform3 "$\text{Left}_{it}$"
lab var credittodeposits_lag "$\text{Credit to deposits}_{it-1}$"
lab var bankconcentr_lag "$\text{Bank concentration}_{it-1}$"
lab var mktfr "$\text{Market-friendly}_{it}$"
lab var intermktfr "$\text{Election}_{it}$ $\times$ $\text{Market-friendly}_{it}$"
